// Les phrases qui tournent sur l'écran d'attente du pop-out.
//
// C'est le texte le plus lu de la soirée : la salle le regarde entre deux
// parties, pendant que l'animateur configure un jeu, et parfois vingt
// minutes avant le début. Le fond de la liste compte donc autant que le
// reste de l'écran, et elle vit à part du widget parce qu'on y touche
// souvent, et pour d'autres raisons que la mise en page.
//
// LES RÈGLES DE LA LISTE :
//
// Ton québécois, taquin envers la salle au complet, JAMAIS envers un joueur
// en particulier : c'est affiché en gros devant tout le monde, et personne
// n'a demandé à être la vedette.
//
// PAS DE POUCES, pas de manettes. Les buzzers sont de gros boutons qu'on
// abat avec la main; quatre messages y faisaient référence autrefois et
// sonnaient faux devant l'objet posé sur la table.
//
// AUCUN CHIFFRE. Annoncer un pointage avant le début de la partie serait
// faux, et c'est précisément ce qu'on est venu corriger ici.
//
// COURT. Deux lignes à 62 pixels dans une boîte de 1080 : passé une
// soixantaine de caractères, la phrase dépasse la hauteur figée et se fait
// couper. Le test de la liste garde cette limite honnête.
const phrasesAttente = <String>[
  'Le bouton est gros. Personne ne pourra dire qu\'il l\'a manqué.',
  "Personne n'a encore perdu. Profitez-en.",
  'Le pointage est à zéro. Tout le monde est premier.',
  'Ça commence dans pas long.',
  "Le premier à peser l'emporte. Toujours.",
  'Buzzer avant de savoir la réponse : un plan risqué.',
  "Aucune question n'a encore fait de victime.",
  'Que la main la plus rapide gagne.',
  'Prenez une gorgée. Après, ça va vite.',
  'Il y a des bonnes réponses, et il y a des réponses à zéro point.',
  'Vos coéquipiers comptent sur vous. Aucune pression.',
  'On teste vos réflexes dans un instant.',
  'Le silence avant la tempête de buzz.',
  'La main au-dessus du bouton. Respirez.',
  "Ce soir, quelqu'un va buzzer trop vite.",
  'Les remontées spectaculaires commencent toutes à zéro.',
  "Le buzzer ne pardonne pas l'hésitation.",
  'Chacun son tour de briller.',
  'La chance sourit à ceux qui appuient.',
  'Préparez vos meilleures excuses.',
  'Frapper plus fort ne rend pas la réponse meilleure.',
  'Le bouton ne connaît pas la réponse. Vous non plus, peut-être.',
  'On entend qui a buzzé. On voit qui le regrette.',
  'Un gros bouton, une petite hésitation, une longue soirée.',
  'Le bouton encaisse. Votre orgueil, un peu moins.',
  'Quatre boutons, une seule bonne réponse, beaucoup de courage.',
  'Le bouton ne juge pas. Nous, un peu.',
  'On oublie les bonnes réponses. Jamais les mauvaises.',
  "Vous avez tous l'air bien confiants. On verra.",
  'Être sûr de soi et avoir raison, ça fait deux.',
  'Le pointage, lui, se souvient de tout.',
  'Répondre vite est un talent. Répondre juste aussi.',
  "Pas de téléphones. On voit très bien d'ici.",
  'Certains vont briller. Les autres vont apprendre.',
  'Un buzz mal placé se raconte encore des années plus tard.',
  "Vous pouvez encore changer d'équipe. Dans deux minutes, non.",
  "On ne juge pas vos réponses. On les compte, c'est pire.",
  'Le doute est permis. Le silence ne rapporte rien.',
  "Vos souvenirs d'école secondaire vont enfin servir.",
  'Tout le monde est bon au quiz, assis dans son salon.',
  'Tout le monde connaît la réponse une seconde trop tard.',
  '« Je le savais » ne vaut aucun point.',
  'Contester la réponse est un sport. Pas celui de ce soir.',
  'Presque, ça ne se compte pas.',
  'Les lumières savent qui a pesé en premier. Aucun débat.',
  'Le hasard aide. Avoir lu un peu, encore plus.',
  'Une égalité, ça se règle. Rarement dans la bonne humeur.',
  'Personne ne repart sans une histoire à raconter.',
  'Deviner est permis. Deviner avec aplomb, recommandé.',
  'Il y a toujours une question facile. Rarement la vôtre.',
  "Le silence de la salle pèse plus lourd qu'on pense.",
  'Vous allez apprendre des choses. Sur vous, surtout.',
  'La modestie est une belle qualité. Gardez-la pour demain.',
  "Un point, c'est un point. Même tombé du ciel.",
  'Ce soir, aucune excuse. Le bouton est juste là.',
  // Le geste, l'objet, la main.
  'Le bouton a déjà survécu à pire que vous.',
  'Le bouton ne demande pas si vous êtes prêts.',
  'Ça ne se pratique pas, peser. Ça se fait.',
  "Il n'y a rien à préparer. Juste à peser.",
  'Le bouton attend. Il est très patient.',
  "Quatre lumières, une seule s'allume en premier.",
  "La main tremble, le bouton s'en fout.",
  'On a testé le bouton. Il fonctionne. Vous, on verra.',
  "Le bouton n'a pas de bouton pour revenir en arrière.",
  "Peser, c'est s'engager.",
  'Ici, la main va plus vite que le raisonnement.',
  'Le geste est simple. Le moment, moins.',
  // La vitesse et le regret.
  'La demi-seconde de trop existe. Vous allez la rencontrer.',
  "Buzzer d'abord, réfléchir ensuite : audacieux.",
  'La vitesse ouvre la porte. La réponse la referme.',
  "Personne ne gagne en attendant d'être certain.",
  "La première main sur le bouton écrit l'histoire.",
  'Réfléchir longtemps, ça laisse la place aux autres.',
  "Trop vite, c'est un risque. Trop tard, c'est fini.",
  'Il y a un moment parfait pour peser. Il est très court.',
  'Attendre la fin de la question est une stratégie. Risquée.',
  'Le regret arrive toujours une seconde après le buzz.',
  'Se retenir de peser, ça demande du caractère.',
  'Le doute prend une seconde. Le buzz en prend moins.',
  // Les certitudes et l'orgueil.
  'La confiance ne se convertit pas en points.',
  'Ce soir, vos certitudes passent au test.',
  'Se souvenir et savoir, on va faire la différence.',
  'Il y a ceux qui savent, et ceux qui pensent savoir.',
  "Personne ici n'est aussi bon qu'il le pense. Nous non plus.",
  "L'assurance, ça paraît bien. Jusqu'à la troisième question.",
  "Vous êtes tous d'accord? Parfait. Quelqu'un a tort.",
  "Personne n'a jamais changé une réponse en la répétant.",
  'La modestie arrive vite. En général à la deuxième manche.',
  'Personne ne se pense mauvais avant de commencer.',
  "Vos exploits d'autrefois ne comptent pas ce soir.",
  'On va découvrir qui bluffe bien.',
  // Les équipes et les alliances.
  "Les alliances tiennent jusqu'à la première mauvaise réponse.",
  "Une équipe, c'est quelqu'un avec qui partager la faute.",
  "Choisissez bien votre monde. C'est trop tard après.",
  "Le voisin de table n'est pas une source fiable.",
  'Dans une équipe, il y en a toujours un qui savait.',
  "Se consulter, c'est bien. C'est aussi plus lent.",
  'Personne ne perd tout seul ici. Consolez-vous avec ça.',
  'Votre équipe vous fait confiance. Pour le moment.',
  'On se rappelle qui a insisté pour la mauvaise réponse.',
  "L'union fait la force. Parfois la confusion aussi.",
  // La salle, les témoins.
  "La salle est témoin. C'est le pire des jurys.",
  'Ici, tout le monde voit tout. Surtout les erreurs.',
  "Il n'y a pas de reprise vidéo. Il y a des témoins.",
  "Crier la réponse d'à côté, ça s'entend.",
  'Les autres tables écoutent. Elles prennent des notes.',
  'Ce soir, il y a plus de spectateurs que de héros.',
  "Personne ne regarde ailleurs quand une lumière s'allume.",
  'La salle applaudit vite et oublie lentement.',
  // La mémoire, ce qui reste de l'école.
  "La culture générale, c'est du hasard bien rangé.",
  'Ce que vous avez lu distraitement compte quand même.',
  'Votre tête a tout gardé. Elle refuse de le sortir vite.',
  'Les réponses sont dans votre tête. Le chemin, moins clair.',
  "Personne n'a révisé. Ça va se voir.",
  'Les connaissances inutiles ont enfin leur soirée.',
  'La mémoire est bonne. Sous pression, un peu moins.',
  'Vous en savez plus que vous pensez. Moins que vous dites.',
  "Apprendre par cœur n'aide pas. Avoir écouté, oui.",
  'Rien de ce soir ne sera à votre examen. Tant mieux.',
  // L'animateur et le règlement.
  "L'animateur a toujours raison. C'est dans le règlement.",
  'Le règlement est court. Les interprétations, non.',
  "On note la réponse. Le reste, c'est du bruit.",
  "Négocier un point n'a jamais marché. Essayez pareil.",
  'Les décisions sont finales. Les soupirs sont permis.',
  "L'animateur voit la réponse. Vous, vous devinez.",
  'Le micro appartient à une seule personne ce soir.',
  "Les questions sont écrites d'avance. Vos excuses, non.",
  // L'attente elle-même.
  'Encore quelques secondes de paix.',
  'Profitez du calme. Il ne reste pas longtemps.',
  'Le dernier moment tranquille de la soirée.',
  'On règle deux, trois affaires et on commence.',
  'Le temps de vous installer, et ça part.',
  "Rien n'est commencé. Tout est encore possible.",
  "La soirée n'a pas encore choisi son gagnant.",
  'Personne en avance, personne en retard.',
  'Étirez-vous le bras. On arrive.',
  'Les vantardises ont commencé avant la partie.',
  // Le hasard.
  'Un bon hasard vaut un bon souvenir.',
  'La chance existe. Elle change souvent de table.',
  'Le hasard donne des points. Il les reprend aussi.',
  'Il faut être chanceux. Il vaut mieux être rapide.',
  'Une réponse au hasard bien placée devient une légende.',
  'Personne ne se vante de deviner. Tout le monde le fait.',
  "Choisir au hasard et avoir raison, c'est presque du talent.",
  'Les coups de chance comptent pour de vrai.',
  // Ce qui va se raconter après.
  'Demain, le pointage sera oublié. Pas ce soir.',
  'Il y aura des explications. Aucune ne changera rien.',
  'Ce soir va se raconter. La version va changer.',
  'La revanche va se demander avant la dernière question.',
  'Perdre est temporaire. Le rappeler à quelqu\'un, éternel.',
  'Les meilleures histoires de la soirée seront à moitié vraies.',
  'Il va y avoir un débat sur une question. Garanti.',
  'La soirée finit toujours par une histoire de bouton.',
  'Quelqu\'un va vouloir rejouer la même question. Non.',
  'Vous allez tous dire que la question était mal posée.',
  // Les lumières et le son : le matériel se mêle de la conversation.
  'La lumière ne ment pas. Elle est juste rapide.',
  'Un son, une lumière, et tout le monde comprend.',
  "Le son du buzz s'entend jusqu'au fond de la salle.",
  "Quand ça sonne, il est déjà trop tard pour changer d'idée.",
  'Un buzz, et toute la salle tourne la tête.',
  // Les stratégies douteuses.
  'Regarder ailleurs pendant une question ne rend pas invisible.',
  'Faire semblant de réfléchir ne trompe personne.',
  'Souffler la réponse, ça se voit dans les visages.',
  'Les stratégies compliquées finissent toutes pareil.',
  'Copier son voisin marche mieux quand le voisin sait.',
  // Le nom d'équipe, cette œuvre.
  "Un bon nom d'équipe ne donne aucun point. Ça paraît bien pareil.",
  "Les noms d'équipe promettent beaucoup. La soirée décidera.",
  'Le nom est choisi. Reste à le mériter.',
  "Le nom d'équipe a demandé plus d'effort que la préparation.",
  // Les autres manches de la soirée.
  "Il n'y a pas juste des questions ce soir.",
  'Certaines manches ne pardonnent pas. Vous verrez laquelle.',
  'Il y a une manche que personne ne voit venir.',
  'Toutes les manches ne se gagnent pas avec la mémoire.',
  'Il va falloir écouter avant de peser. Nouveau concept.',
  // Le trac, le corps qui parle.
  'Les mains deviennent moites vers la deuxième question.',
  'Le trac est normal. Il passe au premier point.',
  'Respirez par le nez. Le reste va suivre.',
  'Votre cœur a compris avant vous que ça commence.',
  'Personne ne remarque que vous êtes nerveux. Sauf tout le monde.',
  // Le temps qui presse.
  "Le temps file plus vite quand c'est votre tour.",
  'Le chrono ne négocie pas.',
  "Quelques secondes, c'est court. Sauf devant une salle.",
  'Le compte à rebours rend tout le monde moins brillant.',
  // La sagesse populaire, détournée.
  "Qui ne tente rien n'a rien. Qui tente tout se trompe souvent.",
  'La nuit porte conseil. La question, non.',
  'Mieux vaut tard que jamais. Sauf ici.',
  "L'important, c'est de participer. C'est ce qu'on dit après.",
  "Toute vérité n'est pas bonne à crier.",
  // L'écran lui-même.
  'Cet écran va se taire dès que ça commence.',
  "Vous lisez encore. C'est signe qu'on a le temps.",
  'Ces phrases changent toutes seules. Pas vos réponses.',
  'Cet écran vous prépare mentalement. Ça ne marche pas.',
  // Ceux qui regardent sans jouer.
  'Ceux qui regardent connaissent toujours la réponse.',
  'Les meilleurs joueurs de la soirée sont assis dans le fond.',
  "Personne ne juge mieux qu'un spectateur.",
  "Il y a toujours quelqu'un qui répond sans jouer.",
  // La soirée, tout simplement.
  'La soirée est jeune. Vos certitudes aussi.',
  'Il reste du temps pour un dernier verre. Pas beaucoup.',
  'Tout le monde est ici pour gagner. Un seul va y arriver.',
  'On commence par une facile. Ou pas.',
];
